name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get submodule
      run:  git submodule update --init --recursive
    - name: install deps
      run: |
          sudo make install-deps
          make /opt/wasi-sdk
    - name: make
      run: make
    - name: make test
      run: make test
    - name: examples
      run: make -C examples
